[package]
name = "rocket-test"
version = "0.2.0"
authors = ["Roman Proskuryakov <humbug@deeptown.org>", "Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2024"

[dependencies]
getopts = "0.2"
rocket = "0.5"
